version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql:/sql:ro
      - ./pgdata:/var/lib/postgresql/data
  api:
    image: postgrest/postgrest:v9.0.0
    ports:
      - "3000:3000"
    links:
      - postgres:postgres
    environment:
      # a good practice would've been to create a separate non-superuser for postgrest
      PGRST_DB_URI: postgres://root:password@postgres:5432/root
      # default schema to be served (reuse existing "public")
      PGRST_DB_SCHEMA: public
      # role if bad or missing jwt (must exist)
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: this32BytesOrMoreStringIsUsedToSignAndCheckJWT # for JWT check
      PGRST_APP_SETTINGS_JWT_SECRET: this32BytesOrMoreStringIsUsedToSignAndCheckJWT # for JWT sign
    depends_on:
      - postgres
  httpd:
    image: nginx:1
    ports:
      - "80:80"
    links:
      - api:api
    environment:
      - POSTGREST_HOST=api
      - POSTGREST_PORT=3000
      - VOSK_EN_HOST=vosken
      - VOSK_EN_PORT=2701
      - VOSK_TH_HOST=voskth
      - VOSK_TH_PORT=2700
    volumes:
      - ./nginx.conf:/nginx.tpl:ro
      - ./static:/etc/nginx/html/static:ro
      - ./media:/etc/nginx/html/media:ro
    command: bash -c "
        envsubst '$$POSTGREST_HOST,$$POSTGREST_PORT,$$VOSK_EN_HOST,$$VOSK_EN_PORT,$$VOSK_TH_HOST,$$VOSK_TH_PORT' < /nginx.tpl > /etc/nginx/nginx.conf &&
        nginx -g 'daemon off; error_log /dev/stderr info;'"
    depends_on:
      - api
  vosken:
    image: sirinyao/kaldi-en-webrtc:v1
    ports:
      - "2701:2701"
  voskth:
    image: sirinyao/kaldi-th-webrtc:v1
    ports:
      - "2700:2700"